import type { Metadata } from 'next'
import './globals.css'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function ClientLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='wellaper'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
